In [5]:
import numpy as np
from sklearn.datasets import make_blobs

In [176]:
X, y= make_blobs(centers=2)

In [177]:
from sklearn.preprocessing import MinMaxScaler
mmsX = MinMaxScaler()
mmsY = MinMaxScaler()

In [178]:
x = mmsX.fit_transform(X)
Y = mmsY.fit_transform(y.reshape(-1, 1))


c:\users\yashwanth chawat\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


In [185]:
def optimize(X, y, epochs, rate):
    w = np.random.random((X.shape[1], 1))
    b = np.random.randn(1)[0]
    for i in range(epochs):
        z = np.dot(X, w) + b
        a = sigmoid(z)
        j = -((np.dot(y.T , np.log(a)) + np.dot((1 - y).T ,np.log(1 - a))))/len(y)
        df = (a - y.reshape((100 ,1)))
        err = np.sum(df)/len(y)
        w = w - rate*np.dot(X.T, df)
        b = b - rate*sum(df)
        print("Loss: " , j)
    return w , b

In [186]:
w , b = optimize(x, Y, 5000 ,0.05)

Loss:  [[ 0.88072387]]
Loss:  [[ 0.68282261]]
Loss:  [[ 0.51939489]]
Loss:  [[ 0.43712718]]
Loss:  [[ 0.37383507]]
Loss:  [[ 0.32957174]]
Loss:  [[ 0.29542723]]
Loss:  [[ 0.26807091]]
Loss:  [[ 0.24546238]]
Loss:  [[ 0.22645367]]
Loss:  [[ 0.2102627]]
Loss:  [[ 0.19631721]]
Loss:  [[ 0.18418669]]
Loss:  [[ 0.17354192]]
Loss:  [[ 0.16412747]]
Loss:  [[ 0.15574248]]
Loss:  [[ 0.14822703]]
Loss:  [[ 0.14145239]]
Loss:  [[ 0.13531385]]
Loss:  [[ 0.12972539]]
Loss:  [[ 0.12461578]]
Loss:  [[ 0.1199255]]
Loss:  [[ 0.1156045]]
Loss:  [[ 0.11161036]]
Loss:  [[ 0.10790691]]
Loss:  [[ 0.10446312]]
Loss:  [[ 0.10125223]]
Loss:  [[ 0.09825105]]
Loss:  [[ 0.09543937]]
Loss:  [[ 0.09279948]]
Loss:  [[ 0.09031584]]
Loss:  [[ 0.08797473]]
Loss:  [[ 0.085764]]
Loss:  [[ 0.08367284]]
Loss:  [[ 0.08169161]]
Loss:  [[ 0.07981169]]
Loss:  [[ 0.07802534]]
Loss:  [[ 0.0763256]]
Loss:  [[ 0.07470616]]
Loss:  [[ 0.07316136]]
Loss:  [[ 0.07168602]]
Loss:  [[ 0.07027545]]
Loss:  [[ 0.06892538]]
Loss:  [[ 0.06763

Loss:  [[ 0.00429601]]
Loss:  [[ 0.00429334]]
Loss:  [[ 0.00429068]]
Loss:  [[ 0.00428802]]
Loss:  [[ 0.00428536]]
Loss:  [[ 0.0042827]]
Loss:  [[ 0.00428005]]
Loss:  [[ 0.0042774]]
Loss:  [[ 0.00427476]]
Loss:  [[ 0.00427212]]
Loss:  [[ 0.00426948]]
Loss:  [[ 0.00426685]]
Loss:  [[ 0.00426422]]
Loss:  [[ 0.00426159]]
Loss:  [[ 0.00425897]]
Loss:  [[ 0.00425635]]
Loss:  [[ 0.00425374]]
Loss:  [[ 0.00425113]]
Loss:  [[ 0.00424852]]
Loss:  [[ 0.00424591]]
Loss:  [[ 0.00424331]]
Loss:  [[ 0.00424071]]
Loss:  [[ 0.00423812]]
Loss:  [[ 0.00423553]]
Loss:  [[ 0.00423294]]
Loss:  [[ 0.00423035]]
Loss:  [[ 0.00422777]]
Loss:  [[ 0.0042252]]
Loss:  [[ 0.00422262]]
Loss:  [[ 0.00422005]]
Loss:  [[ 0.00421748]]
Loss:  [[ 0.00421492]]
Loss:  [[ 0.00421236]]
Loss:  [[ 0.0042098]]
Loss:  [[ 0.00420725]]
Loss:  [[ 0.0042047]]
Loss:  [[ 0.00420215]]
Loss:  [[ 0.00419961]]
Loss:  [[ 0.00419707]]
Loss:  [[ 0.00419453]]
Loss:  [[ 0.004192]]
Loss:  [[ 0.00418947]]
Loss:  [[ 0.00418694]]
Loss:  [[ 0.004184

Loss:  [[ 0.00295251]]
Loss:  [[ 0.00295133]]
Loss:  [[ 0.00295015]]
Loss:  [[ 0.00294897]]
Loss:  [[ 0.00294779]]
Loss:  [[ 0.00294661]]
Loss:  [[ 0.00294543]]
Loss:  [[ 0.00294426]]
Loss:  [[ 0.00294308]]
Loss:  [[ 0.00294191]]
Loss:  [[ 0.00294074]]
Loss:  [[ 0.00293956]]
Loss:  [[ 0.00293839]]
Loss:  [[ 0.00293722]]
Loss:  [[ 0.00293605]]
Loss:  [[ 0.00293488]]
Loss:  [[ 0.00293372]]
Loss:  [[ 0.00293255]]
Loss:  [[ 0.00293139]]
Loss:  [[ 0.00293022]]
Loss:  [[ 0.00292906]]
Loss:  [[ 0.0029279]]
Loss:  [[ 0.00292674]]
Loss:  [[ 0.00292558]]
Loss:  [[ 0.00292442]]
Loss:  [[ 0.00292326]]
Loss:  [[ 0.0029221]]
Loss:  [[ 0.00292095]]
Loss:  [[ 0.00291979]]
Loss:  [[ 0.00291864]]
Loss:  [[ 0.00291748]]
Loss:  [[ 0.00291633]]
Loss:  [[ 0.00291518]]
Loss:  [[ 0.00291403]]
Loss:  [[ 0.00291288]]
Loss:  [[ 0.00291173]]
Loss:  [[ 0.00291058]]
Loss:  [[ 0.00290944]]
Loss:  [[ 0.00290829]]
Loss:  [[ 0.00290715]]
Loss:  [[ 0.002906]]
Loss:  [[ 0.00290486]]
Loss:  [[ 0.00290372]]
Loss:  [[ 0.002

Loss:  [[ 0.00227129]]
Loss:  [[ 0.00227062]]
Loss:  [[ 0.00226995]]
Loss:  [[ 0.00226928]]
Loss:  [[ 0.00226861]]
Loss:  [[ 0.00226794]]
Loss:  [[ 0.00226727]]
Loss:  [[ 0.0022666]]
Loss:  [[ 0.00226593]]
Loss:  [[ 0.00226526]]
Loss:  [[ 0.00226459]]
Loss:  [[ 0.00226393]]
Loss:  [[ 0.00226326]]
Loss:  [[ 0.00226259]]
Loss:  [[ 0.00226193]]
Loss:  [[ 0.00226126]]
Loss:  [[ 0.0022606]]
Loss:  [[ 0.00225993]]
Loss:  [[ 0.00225927]]
Loss:  [[ 0.0022586]]
Loss:  [[ 0.00225794]]
Loss:  [[ 0.00225727]]
Loss:  [[ 0.00225661]]
Loss:  [[ 0.00225595]]
Loss:  [[ 0.00225529]]
Loss:  [[ 0.00225462]]
Loss:  [[ 0.00225396]]
Loss:  [[ 0.0022533]]
Loss:  [[ 0.00225264]]
Loss:  [[ 0.00225198]]
Loss:  [[ 0.00225132]]
Loss:  [[ 0.00225066]]
Loss:  [[ 0.00225]]
Loss:  [[ 0.00224935]]
Loss:  [[ 0.00224869]]
Loss:  [[ 0.00224803]]
Loss:  [[ 0.00224737]]
Loss:  [[ 0.00224672]]
Loss:  [[ 0.00224606]]
Loss:  [[ 0.0022454]]
Loss:  [[ 0.00224475]]
Loss:  [[ 0.00224409]]
Loss:  [[ 0.00224344]]
Loss:  [[ 0.0022427

Loss:  [[ 0.0017666]]
Loss:  [[ 0.00176621]]
Loss:  [[ 0.00176581]]
Loss:  [[ 0.00176542]]
Loss:  [[ 0.00176503]]
Loss:  [[ 0.00176464]]
Loss:  [[ 0.00176425]]
Loss:  [[ 0.00176386]]
Loss:  [[ 0.00176347]]
Loss:  [[ 0.00176307]]
Loss:  [[ 0.00176268]]
Loss:  [[ 0.00176229]]
Loss:  [[ 0.0017619]]
Loss:  [[ 0.00176151]]
Loss:  [[ 0.00176112]]
Loss:  [[ 0.00176073]]
Loss:  [[ 0.00176035]]
Loss:  [[ 0.00175996]]
Loss:  [[ 0.00175957]]
Loss:  [[ 0.00175918]]
Loss:  [[ 0.00175879]]
Loss:  [[ 0.0017584]]
Loss:  [[ 0.00175801]]
Loss:  [[ 0.00175762]]
Loss:  [[ 0.00175724]]
Loss:  [[ 0.00175685]]
Loss:  [[ 0.00175646]]
Loss:  [[ 0.00175607]]
Loss:  [[ 0.00175569]]
Loss:  [[ 0.0017553]]
Loss:  [[ 0.00175491]]
Loss:  [[ 0.00175453]]
Loss:  [[ 0.00175414]]
Loss:  [[ 0.00175375]]
Loss:  [[ 0.00175337]]
Loss:  [[ 0.00175298]]
Loss:  [[ 0.0017526]]
Loss:  [[ 0.00175221]]
Loss:  [[ 0.00175182]]
Loss:  [[ 0.00175144]]
Loss:  [[ 0.00175105]]
Loss:  [[ 0.00175067]]
Loss:  [[ 0.00175029]]
Loss:  [[ 0.0017

Loss:  [[ 0.00151384]]
Loss:  [[ 0.00151356]]
Loss:  [[ 0.00151328]]
Loss:  [[ 0.001513]]
Loss:  [[ 0.00151272]]
Loss:  [[ 0.00151243]]
Loss:  [[ 0.00151215]]
Loss:  [[ 0.00151187]]
Loss:  [[ 0.00151159]]
Loss:  [[ 0.00151131]]
Loss:  [[ 0.00151103]]
Loss:  [[ 0.00151075]]
Loss:  [[ 0.00151047]]
Loss:  [[ 0.00151018]]
Loss:  [[ 0.0015099]]
Loss:  [[ 0.00150962]]
Loss:  [[ 0.00150934]]
Loss:  [[ 0.00150906]]
Loss:  [[ 0.00150878]]
Loss:  [[ 0.0015085]]
Loss:  [[ 0.00150822]]
Loss:  [[ 0.00150794]]
Loss:  [[ 0.00150766]]
Loss:  [[ 0.00150738]]
Loss:  [[ 0.0015071]]
Loss:  [[ 0.00150682]]
Loss:  [[ 0.00150654]]
Loss:  [[ 0.00150627]]
Loss:  [[ 0.00150599]]
Loss:  [[ 0.00150571]]
Loss:  [[ 0.00150543]]
Loss:  [[ 0.00150515]]
Loss:  [[ 0.00150487]]
Loss:  [[ 0.00150459]]
Loss:  [[ 0.00150431]]
Loss:  [[ 0.00150404]]
Loss:  [[ 0.00150376]]
Loss:  [[ 0.00150348]]
Loss:  [[ 0.0015032]]
Loss:  [[ 0.00150292]]
Loss:  [[ 0.00150265]]
Loss:  [[ 0.00150237]]
Loss:  [[ 0.00150209]]
Loss:  [[ 0.00150

In [86]:
def sigmoid(X):
    return 1/(1 + np.exp(-X))

In [187]:
w

array([[-17.37644572],
       [-18.47379288]])

In [188]:
x[0]

array([ 0.18127403,  0.34547547])

In [195]:
sigmoid(np.dot(x[3] , w) + b)

array([ 0.00831629])

In [194]:
y[3]

0