In [255]:
import numpy as np
import pandas as pd

In [2]:
ds = pd.read_csv("USA_Housing.csv")

In [3]:
ds.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [336]:
X_data = ds.iloc[:, :5].values
Y_data = ds.iloc[:, -2:-1].values

In [337]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_data, test_size = 0.05, random_state = 101)

In [338]:
from sklearn.preprocessing import StandardScaler
ScalerX = StandardScaler()
ScalerY = StandardScaler()

# from sklearn.preprocessing import MinMaxScaler
# ScalerX = MinMaxScaler()
# ScalerY = MinMaxScaler()

In [339]:
X_train = ScalerX.fit_transform(X_train)
Y_train = ScalerY.fit_transform(Y_train.reshape(-1, 1))

In [340]:
X_test = ScalerX.transform(X_test)
Y_test = ScalerY.transform(Y_test.reshape(-1, 1))

In [356]:
def train(X, Y, lr = 0.05 , epochs = 100):
    W = np.random.random(5).reshape(5, 1)
    b = np.random.random(1).reshape(1, 1)
    for e in range(epochs):
        y_ = np.dot(X, W) + b
        err = (Y - y_)

        loss = np.mean(a = err**2)
        W[0] = W[0] - lr * (-2 * np.mean(X[:, 0] * err.T))
        W[1] = W[1] - lr * (-2 * np.mean(X[:, 1] * err.T))
        W[2] = W[2] - lr * (-2 * np.mean(X[:, 2] * err.T))
        W[3] = W[3] - lr * (-2 * np.mean(X[:, 3] * err.T))
        W[4] = W[4] - lr * (-2 * np.mean(X[:, 4] * err.T))
        
        b = b - lr * (-2 * np.mean(err))
        
        if e % 50 == 0:
            print("epoch ", e, " loss: ", loss)
    return W, b

In [361]:
W, b = train(X_train, Y_train, lr = 0.05, epochs = 150)

epoch  0  loss:  0.747683940161925
epoch  50  loss:  0.08214802778789168
epoch  100  loss:  0.08208899398222398


In [362]:
W

array([[0.6524572 ],
       [0.46467291],
       [0.34061164],
       [0.00689764],
       [0.42796674]])

In [363]:
b

array([[5.57643215e-08]])

In [364]:
X_pred = np.array([80000, 5.69, 7, 4.1, 23050])

In [365]:
X_pred_scaled = ScalerX.transform(X_pred.reshape(1, -1))

In [366]:
X_pred_scaled.shape

(1, 5)

In [367]:
W.shape

(5, 1)

In [368]:
Y_pred = np.dot(X_pred_scaled, W) + b

In [369]:
res = ScalerY.inverse_transform(Y_pred)

In [370]:
res

array([[1233112.49508399]])